const String BASE_URL = "https://example.herokuapp.com";
const String AUTH_URL = BASE_URL + "user";
const String USER_INFO_URL = BASE_URL + "info";
const String POST_URL = BASE_URL + "post";
const String POST_MEDIA_URL = BASE_URL + "media";
const String STORY_URL = BASE_URL + "story";
const String COMMENT_URL = BASE_URL + "comment";
const String LIKE_URL = BASE_URL + "like";
const String FOLLOW_URL = BASE_URL + "follow";